/*
 * Copyright (c) 2020 Victor Antonovich <v.antonovich@gmail.com>
 *
 * This work is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This work is distributed in the hope that it will be useful, but
 * without any warranty; without even the implied warranty of merchantability
 * or fitness for a particular purpose. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 */

package com.github.ykc3.android.usbi2c.app.device.info;

import java.util.List;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by http://www.jsonschema2pojo.org/ from https://i2cdevices.org/devices.json
 */
public class I2cDeviceInfo {
    @SerializedName("part_number")
    @Expose
    private String partNumber;
    @SerializedName("friendly_name")
    @Expose
    private String friendlyName;
    @SerializedName("datasheet")
    @Expose
    private String datasheet;
    @SerializedName("adafruit")
    @Expose
    private String adafruit;
    @SerializedName("sparkfun")
    @Expose
    private String sparkfun;
    @SerializedName("obsolete")
    @Expose
    private boolean obsolete;
    @SerializedName("manufacturer")
    @Expose
    private String manufacturer;
    @SerializedName("is_5v")
    @Expose
    private boolean is5v;
    @SerializedName("is_3v")
    @Expose
    private boolean is3v;
    @SerializedName("is_spi")
    @Expose
    private boolean isSpi;
    @SerializedName("release_date")
    @Expose
    private int releaseDate;
    @SerializedName("scanned_drivers")
    @Expose
    private boolean scannedDrivers;
    @SerializedName("drivers")
    @Expose
    private List<I2cDeviceDriverInfo> i2cDeviceDriverInfos = null;
    @SerializedName("addresses")
    @Expose
    private List<Integer> addresses = null;

    public String getPartNumber() {
        return partNumber;
    }

    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }

    public String getFriendlyName() {
        return friendlyName;
    }

    public void setFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
    }

    public String getDatasheet() {
        return datasheet;
    }

    public void setDatasheet(String datasheet) {
        this.datasheet = datasheet;
    }

    public String getAdafruit() {
        return adafruit;
    }

    public void setAdafruit(String adafruit) {
        this.adafruit = adafruit;
    }

    public String getSparkfun() {
        return sparkfun;
    }

    public void setSparkfun(String sparkfun) {
        this.sparkfun = sparkfun;
    }

    public boolean isObsolete() {
        return obsolete;
    }

    public void setObsolete(boolean obsolete) {
        this.obsolete = obsolete;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public boolean isIs5v() {
        return is5v;
    }

    public void setIs5v(boolean is5v) {
        this.is5v = is5v;
    }

    public boolean isIs3v() {
        return is3v;
    }

    public void setIs3v(boolean is3v) {
        this.is3v = is3v;
    }

    public boolean isIsSpi() {
        return isSpi;
    }

    public void setIsSpi(boolean isSpi) {
        this.isSpi = isSpi;
    }

    public int getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(int releaseDate) {
        this.releaseDate = releaseDate;
    }

    public boolean isScannedDrivers() {
        return scannedDrivers;
    }

    public void setScannedDrivers(boolean scannedDrivers) {
        this.scannedDrivers = scannedDrivers;
    }

    public List<I2cDeviceDriverInfo> getI2cDeviceDriverInfos() {
        return i2cDeviceDriverInfos;
    }

    public void setI2cDeviceDriverInfos(List<I2cDeviceDriverInfo> i2cDeviceDriverInfos) {
        this.i2cDeviceDriverInfos = i2cDeviceDriverInfos;
    }

    public List<Integer> getAddresses() {
        return addresses;
    }

    public void setAddresses(List<Integer> addresses) {
        this.addresses = addresses;
    }

    public static class I2cDeviceDriverInfo {
        @SerializedName("link")
        @Expose
        private String link;
        @SerializedName("title")
        @Expose
        private String title;

        public String getLink() {
            return link;
        }

        public void setLink(String link) {
            this.link = link;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
    }
}
